server: 
  port: 8081
management: 
  endpoints: 
    web: 
      expose: refresh
      exposure: 
        include: refresh
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://127.0.0.1:8080/eureka/         