server: 
  port: 8082
spring: 
  cloud: 
    config: 
      server: 
        native: 
          searchLocations: classpath:config/,classpath:config/licensingservice,classpath:config/organizationservice
  profiles: 
    active: native