example.property: "I AM IN THE DEFAULT"

spring.jpa.show-sql: "true"
spring.datasource.url: "jdbc:mysql://127.0.0.1:3306/cloudexample"
spring.datasource.username: "springuser"
spring.datasource.password: "ThePassword"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"

